### ISSUE TITLE
Discuss alternative Implementation

### ISSUE THREAD

**Issue by ccremer** [gentics/kubernetes-zfs-provisioner#11]
Hi all

A while ago I forked this repo and did some changes. Now, it's almost a completely rewritten, also comes now with a container image and Helm chart: https://github.com/ccremer/kubernetes-zfs-provisioner

Would you be interested in a PR where we could discuss the changes so we could merge this into one codebase?
If you are not interested in this or not further maintaining it (which would be totally ok), would you be ok if I remove the fork link between these repos, so I can maintain my repo without any link to gentics/kubernetes-zfs-provisioner ? (I'd have to delete my repo and then re-import the git history I guess but that's just technicality). Or maybe just a link in the readme to my fork...?

Main changes:
* The provisioner runs now in-cluster and requires SSH to a target host
* Creates PVs from StorageClasses, volume configuration is provided via StorageClass parameters.
* Can manage volumes for multiple ZFS hosts (requires a StorageClass each)
* Uses a repository-neutral instance name `pv.kubernetes.io/zfs`
* Supports NFS and now also HostPath volumes.
* Recommended & only supported installation method is the Docker image. The image doesn't contain ZFS itself, but rather the ZFS commands are wrapped in SSH and executed on the remote host.
* Also I wrote a Helm Chart for easy installation of the boilerplate manifests (https://github.com/ccremer/charts/tree/master/kubernetes-zfs-provisioner)
* Adds CI/CD workflows using Github Actions

Cheers and thanks for this awesome project :)

**Comment by Jotschi** [comment]
@ccremer Glad to hear that you found the project useful. We are still using it in production but have no plans to upgrade or modify it. I'm not the owner of the project so I can't make any decision regarding licensing related question. Maybe @mephinet can answer this.

I personally have no problem with removing the fork link or even redirecting vistors of this repo to yours. I'll let you know how this turns out on monday.

**Comment by Jotschi** [comment]
Hi @ccremer , yes you can remove the link between the repos. Thanks for the great work! We'll archive this one and set a redirect to your repo.

We would welcome a credit in your readme. Something like "Thanks to Gentics (https://www.gentics.com/genticscms/index.en.html) for open sourcing the initial version" would be awesome.

We are planning to switch to trident in the future and have no bandwidth / plans to extend this provisioner.
Kudos also to @simontesar for the initial implementation.
