### ISSUE TITLE
zpool not connecting

### ISSUE THREAD

**Issue by mhabicht** [gentics/kubernetes-zfs-provisioner#9]
I am attempting to configure my deployment to mount a zpool, this is what I have but I know it is wrong. 

ERROR:
Normal  ExternalProvisioning  3m (x262 over 1h)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "gentics.com/zfs" or manually created by system administrator
Error from server (NotFound): persistentvolumeclaims "claim" not found

**Worker node:**
# zpool list
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
vol0  29.8G   130K  29.7G         -     0%     0%  1.00x  ONLINE  -

**Master node:**
# more zfs_storage_class.yaml 
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: zfs
provisioner: gentics.com/zfs

# more zfs_pod.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zfspod
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
        interface: zfs
    spec:
      hostname: zfspod
      containers:
      - name: ubuntu
        image: library/ubuntu:16.04
        ports:
        - containerPort: 22
        command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
        volumeMounts:
        - name: zfsvol
          mountPath: /u01
      restartPolicy: Always
      volumes:
      - name: zfsvol
        persistentVolumeClaim:
          claimName: zfsclaim

---
apiVersion: v1
kind: Service
metadata:
  name: zfs
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    interface: zfs
  type: LoadBalancer
  loadBalancerIP: 10.246.4.207
  sessionAffinity: ClientIP

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zfsclaim
  annotations:
    volume.beta.kubernetes.io/storage-class: "zfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30G

**Comment by simt2** [comment]
Without logs or anything suggesting that that there's a problem with the software developed here, we cannot help you. Please seek general Kubernetes support somewhere else and/or open a new issue containing information about e.g. a bug encountered.
